### PR TITLE
ABQM - worker information

### PR DESCRIPTION
**Pull request by kthare10**
- Added a node for each worker connected to the Site Composite Node in ABQM; include capacities and capacity_allocations
- Added a component node for each component/model pair including capacities and capacity_allocations
- Indicate site as Active when a specific worker is in Maintenance including the workers' maintenance state as well

#313

### CODE REVIEW

**Comment by kthare10** [comment]
@ibaldin - This also requires changes in user interfacing FIM object `CompositeNode` to return `nodes` associated with a `Site` thus enabling the user to be able to check per worker information.

**Review by ibaldin — COMMENTED** [review]
So I guess for query level 2 in addition to a 'site' node there will be 'worker' nodes that 'site' node 'has'. Worker nodes 'has' components. Are the components then doubled up then - they are attached to the 'site' node (in summed up quantities for the site) and also to individual workers, like in ARM?

**Comment by kthare10** [comment]
Currently they are doubled up at the site level and worker level, but we can remove them at site level to avoid duplicacy.

**Review by ibaldin — APPROVED** [review]
+1

**Pull request merged**
