### PR TITLE
check for dependency only for modify in ExtendTicket

### PR DESCRIPTION
**Pull request by kthare10**
Addresses #248 
Tested on Beta

Needs to deployed on production Orchestrator to address the renew issue.

### CODE REVIEW

**Comment by ibaldin** [comment]
Could you explain why it doesn't work for already created slices? What types of slices does this affect? I'm just thinking if we need to post any kind of announcement if it can affect a large number of experiments?

**Review by ibaldin — APPROVED** [review]
+1

**Comment by kthare10** [comment]
Renew slice triggers ExtendTicket for all slivers to the Broker followed by Extend Lease.
ExtendTicket is also triggered for modify operation. It was updated in 1.4 for Network Service Reservations to check for their dependencies before extending them. 
**Modify Scenario:**
Network Service to which interface from a new VM are added would result in ExtendTicket, but Orchestrator waits for the new VM to be ticketed before triggering an Extend Ticket for Network Service.

The above change resulted in ExtendTicket for Renew to fail because of an assertion failure which is only true for modify.

Renew slice should work for existing slices if they do not have slivers in `ExtendingTicket` state. Slices with network services which were extended post upgrade would have this pending state for failed slivers.

Based on Management CLI, I found following slices in this state on production:
- Slice JanusController(cf8a634f-2c93-4a0f-a5e8-6952a7e96023) Owner:kissel@es.net
- Slice timestamptest-lib(d08893f9-e1a4-4400-af29-6bfed497179e) Owner:pinyi.shi@uky.edu
- Slice bbr-dominance-line(cbef45bf-5029-4da8-85b8-49f8aa1b2c20) Owner:ashusri@nyu.edu
- Slice 5g@1675268603(30b37c6c-c2c8-4fb3-949c-0535c0c51732) Owner:shijunxiao@arizona.edu
- Slice v4gateway@1675276993(5e4c5828-0fc5-4e8d-b13c-644c5c1700dd) Owner:shijunxiao@arizona.edu
- Slice Computing(115d86bf-8ab1-4f30-9713-91aa31ef1ccf)  Owner:ssamine@clemson.edu

**Comment by ibaldin** [comment]
I see, we should let them know individually, thank you for checking this. Seems like a fairly minor impact.

**Comment by kthare10** [comment]
Sounds good, I will deploy the fix and then send an email to the above listed slice owner about the impact.

**Pull request merged**
